[phases.setup]
cmds = ["rm -rf /app/.venv"]

[phases.install]
cmds = ["python -m venv /app/.venv", "/app/.venv/bin/pip install --no-cache-dir --upgrade pip", "/app/.venv/bin/pip install --no-cache-dir -r requirements.txt"]